---
overrides:
  {{- range $tenant, $spec := .Stack.Limits.Tenants }}
  {{ $tenant }}:
  {{- if $l := $spec.IngestionLimits -}}
    {{ if $l.IngestionRate }}
    ingestion_rate_mb: {{ $l.IngestionRate }}
    {{- end -}}
    {{ if $l.IngestionBurstSize }}
    ingestion_burst_size_mb: {{ $l.IngestionBurstSize }}
    {{- end -}}
    {{ if $l.MaxLabelNameLength }}
    max_label_name_length: {{ $l.MaxLabelNameLength }}
    {{- end -}}
    {{ if $l.MaxLabelValueLength }}
    max_label_value_length: {{ $l.MaxLabelValueLength }}
    {{- end -}}
    {{ if $l.MaxLabelNamesPerSeries }}
    max_label_names_per_series: {{ $l.MaxLabelNamesPerSeries }}
    {{- end -}}
    {{ if $l.MaxLineSize }}
    max_line_size: {{ $l.MaxLineSize }}
    {{- end -}}
    {{ if $l.MaxGlobalStreamsPerTenant }}
    max_global_streams_per_user: {{ $l.MaxGlobalStreamsPerTenant }}
    {{- end }}
    {{- if $l.PerStreamRateLimit }}
    per_stream_rate_limit: {{ $l.PerStreamRateLimit }}MB
    {{- end }}
    {{- if $l.PerStreamRateLimitBurst }}
    per_stream_rate_limit_burst: {{ $l.PerStreamRateLimitBurst }}MB
    {{- end }}
  {{- end -}}
  {{- if $l := $spec.QueryLimits -}}
    {{ if $l.MaxEntriesLimitPerQuery }}
    max_entries_limit_per_query: {{ $spec.QueryLimits.MaxEntriesLimitPerQuery }}
    {{- end -}}
    {{ if $spec.QueryLimits.MaxChunksPerQuery }}
    max_chunks_per_query: {{ $spec.QueryLimits.MaxChunksPerQuery }}
    {{- end -}}
    {{ if $spec.QueryLimits.MaxQuerySeries }}
    max_query_series: {{ $spec.QueryLimits.MaxQuerySeries }}
    {{- end -}}
    {{ if $spec.QueryLimits.QueryTimeout }}
    query_timeout: {{ $spec.QueryLimits.QueryTimeout }}
    {{- end }}
    {{- if $spec.QueryLimits.CardinalityLimit }}
    cardinality_limit: {{ $spec.QueryLimits.CardinalityLimit }}
    {{- end }}
  {{- end -}}
  {{- with $spec.Retention }}
    retention_period: {{ .Days }}d
    {{- with .Streams }}
    retention_stream:
    {{- range . }}
    - selector: '{{ .Selector }}'
      priority: {{ .Priority }}
      period: {{ .Days }}d
    {{- end }}
    {{- end }}
  {{- end }}
  {{- end -}}
